CREATE TABLE IF NOT EXISTS mu_gems (
  id INT AUTO_INCREMENT PRIMARY KEY,
  item_id VARCHAR(32) UNIQUE,
  code VARCHAR(16),
  item_type INT,
  item_index INT,
  name_zh VARCHAR(128),
  name_en VARCHAR(128),
  name_kr VARCHAR(128),
  category VARCHAR(64),
  description TEXT,
  inventory_size VARCHAR(16),
  class_limit TEXT,
  icon_path VARCHAR(255),
  icon_url VARCHAR(255),
  source_url VARCHAR(255)
) DEFAULT CHARSET=utf8mb4;
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014420','14-420',14,420,'[绑定]神秘之石','[Bound]Mysterious Stone','[귀속]신비의돌','宝石/货币','具有神秘能力的石头。可用于精通/传奇道具，可变更属性。[注意] 可能比所具有的属性变得更低。神秘之石属性概率可在官网概率信息中确认。','1 x 1','','icons/so_stone01.png','https://mu.dvg.cn/source/n_itemlitpic/so_stone01.png','https://mu.dvg.cn/item_info.php?id=4581') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014417','14-417',14,417,'血色天使之魂变换标志','Bloodangel Soul Transform Symbol','블러드엔젤의혼 변환 징표','宝石/货币','Speed server [绑定]把+11/13/15强套装防具和该道具哥布林合成之后可变换为[血色天使之魂]的道具。','1 x 1','','icons/rareitem_ticket7.png','https://mu.dvg.cn/source/n_itemlitpic/rareitem_ticket7.png','https://mu.dvg.cn/item_info.php?id=4578') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014413','14-413',14,413,'奇迹的铜币','Coin of Miracle','기적의 동전','宝石/货币','在奇迹商店使用的货币道具。请去找幻术园奇迹商人摩斯。[注意] 装备栏不可叠加，请确保空间充足。','1 x 1','','icons/coin7.png','https://mu.dvg.cn/source/n_itemlitpic/coin7.png','https://mu.dvg.cn/item_info.php?id=4574') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014345','14-345',14,345,'神秘之石','Mysterious Stone','신비의돌','宝石/货币','具有神秘能力的石头。可用于精通/传奇道具，可变更属性。[注意] 可能比所具有的属性变得更低。神秘之石属性概率可在官网概率信息中确认。','1 x 1','','icons/so_stone01.png','https://mu.dvg.cn/source/n_itemlitpic/so_stone01.png','https://mu.dvg.cn/item_info.php?id=4520') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014161','14-161',14,161,'提高宝石','Jewel of Elevation','상승의보석','宝石/货币','用于强化道具的宝石。','1 x 1','','icons/lucky_items02.png','https://mu.dvg.cn/source/n_itemlitpic/lucky_items02.png','https://mu.dvg.cn/item_info.php?id=4395') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014160','14-160',14,160,'延长宝石','Jewel of Extension','연장의보석','宝石/货币','用于修理幸运道具耐久度的宝石。','1 x 1','','icons/lucky_items01.png','https://mu.dvg.cn/source/n_itemlitpic/lucky_items01.png','https://mu.dvg.cn/item_info.php?id=4394') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014044','14-44',14,44,'高级进化宝石','Higher refining stone','상급 제련석','宝石/货币','使用于赋予再生额外属性或去除再生属性的合成材料。适用+9强化等级以上、赋予再生额外属性、赋予3条再生属性数值在高级以上的道具。','1 x 1','','icons/HighRefineStone.png','https://mu.dvg.cn/source/n_itemlitpic/HighRefineStone.png','https://mu.dvg.cn/item_info.php?id=4279') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014043','14-43',14,43,'初级进化宝石','Lower refining stone','하급 제련석','宝石/货币','赋予再生额外属性时使用。适用+9强化等级以上、赋予再生额外属性、赋予3条再生属性数值在高级以上的道具。','1 x 1','','icons/LowRefineStone.png','https://mu.dvg.cn/source/n_itemlitpic/LowRefineStone.png','https://mu.dvg.cn/item_info.php?id=4278') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014042','14-42',14,42,'再生宝石','Jewel of Harmony','조화의보석','宝石/货币','用于强化道具的宝石。','1 x 1','','icons/jos.png','https://mu.dvg.cn/source/n_itemlitpic/jos.png','https://mu.dvg.cn/item_info.php?id=4277') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014041','14-41',14,41,'再生原石','Gemstone','원석','宝石/货币','再生宝石相关原石道具，可作为合成/提炼材料使用。','1 x 1','','icons/rs.png','https://mu.dvg.cn/source/n_itemlitpic/rs.png','https://mu.dvg.cn/item_info.php?id=4276') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014031','14-31',14,31,'守护宝石','Jewel of Guardian','수호보석','宝石/货币','守护类宝石道具，可用于特定系统强化/合成。','1 x 1','','icons/suho.png','https://mu.dvg.cn/source/n_itemlitpic/suho.png','https://mu.dvg.cn/item_info.php?id=4266') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014022','14-22',14,22,'创造宝石','Jewel of Creation','창조의보석','宝石/货币','创造类宝石道具，可用于特定系统合成。','1 x 1','','icons/jewel22.png','https://mu.dvg.cn/source/n_itemlitpic/jewel22.png','https://mu.dvg.cn/item_info.php?id=4259') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014016','14-16',14,16,'生命宝石','Jewel of Life','생명의보석','宝石/货币','用于装备追加属性相关强化的宝石。','1 x 1','','icons/Jewel03.png','https://mu.dvg.cn/source/n_itemlitpic/Jewel03.png','https://mu.dvg.cn/item_info.php?id=4253') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014014','14-14',14,14,'灵魂宝石','Jewel of Soul','영혼의보석','宝石/货币','用于装备强化的核心宝石。','1 x 1','','icons/Jewel02.png','https://mu.dvg.cn/source/n_itemlitpic/Jewel02.png','https://mu.dvg.cn/item_info.php?id=4251') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1014013','14-13',14,13,'祝福宝石','Jewel of Bless','축복의보석','宝石/货币','用于装备强化的核心宝石。','1 x 1','','icons/Jewel01.png','https://mu.dvg.cn/source/n_itemlitpic/Jewel01.png','https://mu.dvg.cn/item_info.php?id=4250') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
INSERT INTO mu_gems (item_id,code,item_type,item_index,name_zh,name_en,name_kr,category,description,inventory_size,class_limit,icon_path,icon_url,source_url) VALUES ('1012015','12-15',12,15,'玛雅之石','Jewel of Chaos','혼돈의보석','宝石/货币','玛雅合成相关核心材料。','1 x 1','魔法师、剑士、弓箭手、魔剑士、圣导师、符文法师、疾风、光明法师、圣光学者、炼金术士','icons/Jewel15.png','https://mu.dvg.cn/source/n_itemlitpic/Jewel15.png','https://mu.dvg.cn/item_info.php?id=3681') ON DUPLICATE KEY UPDATE name_zh=VALUES(name_zh);
